### ISSUE TITLE
Album artist is not picked correctly

### ISSUE THREAD

**Issue by maliayas** [Rafiuth/Soggfy#32]
It seems that Soggfy is picking the first one of the artists as the album artist. However album artist is an independant property on its own. Take this song for example:

https://open.spotify.com/track/4AVdIujJQitL1VliBJG7xw?si=777da3ca8f6b48bd

Here the album artist is Shankar Jaikishan but Soggfy ignores it and uses the regular artist as album artist.

**Comment by Rafiuth** [comment]
Should be fixed in v2.2.16. The "album_artist" field in the embedded metadata should now be correct, but the download path will keep using the regular/first artist.

This is because Spotify doesn't provide this info everywhere (e.g. in the playlist rows, which is used by the status indicator), but it also preserves backwards compatibility.
