### ISSUE TITLE
Download Issue 

### ISSUE THREAD

**Issue by Mifo001** [Rafiuth/Soggfy#89]
So have been using Soggfy for around a month now and love it, but for some reason it doesn't download the last song in the playlist. Any ideas? Thank you.

**Comment by Rafiuth** [comment]
Seems like spotify is cutting off the playback when changing playlists somehow and soggfy never sees that the track has ended. I'll take a closer look if I get around to messing with soggfy soon, but no promises.

Maybe one way to workaround this would be to add the playlist to queue instead of using the play button, but that would not be very convenient for very long playlists.

**Comment by Mifo001** [comment]
Thank you Rafiuth, I will give that a try. Will also try adding an additional song to the playlist to see if that sorts it out.

**Comment by Rafiuth** [comment]
This should've been fixed in [v2.7.0](https://github.com/Rafiuth/Soggfy/releases/tag/v2.7.0). If you try it and it's still happening, please re-open this issue.
