### ISSUE TITLE
Set spotify quality to "very high" when it's not available

### ISSUE THREAD

**Issue by HanaMcHanaface** [Rafiuth/Soggfy#97]
A problem I had that also a lot of others seem to have as well, is that the quality option in settings only goes to "high", not "very high".  Which means bitrate is about 160kbps instead of 320kbps. This is while having a premium account, which should allow you the higher quality. Nothing seems to make the option available in spotify itself, but luckily there's a solution!!

I found it here after a lot of searching: https://community.spotify.com/t5/Desktop-Linux/Streaming-quality-does-nothing/m-p/5210294/highlight/true#M20501

This is talking about linux but the process is basically the same on windows:

1. Make sure all quality options are not on "automatic".
2. Go to `%APPDATA%\Spotify\Users` and there you will find a folder with your username. Enter it.
3. Open the file simply named `prefs` and inside make these changes:

```
audio.play_bitrate_non_metered_enumeration=4
audio.play_bitrate_enumeration=4
```

These lines should both be set to `=4`. Now open spotify and enjoy high quality downloads!! I think it would be helpful if this was mentioned in the readme for the future.

You also have to make sure you do not have songs already downloaded with spotify (I'm talking about the spotify donwload here and not soggfy download) and to remove them before downloading with soggfy. Probably a good idea to clear the cache as well.

**Comment by erikZygloxius** [comment]
I found another solution:
During installation Process of SpotX, it asks for customized parameters. Here you have to set -premium (better described here: https://github.com/SpotX-Official/SpotX/discussions/60)

**Comment by Errorhuhn** [comment]
Nice research! 

Today I had the exact same problem and accidentally found the reason (and therefore a different solution) for this bug:
Unfortunatelly, the SpotX Developers removed these settings in the 1.5 release on purpose (https://github.com/SpotX-Official/SpotX/releases/tag/1.5), i think because the mod is mostly used by free users!?

BUT, they have a setting to revert these changes. So, during installation process of SpotX (and therefore also during the installation process of Soggfy), it asks for customized parameters:

Here you have to set **-premium** (I also added -new_theme, but I think this is not necessary)

Beware that you have to do this during a reinstall of Soggfy, as a simple reinstall of SpotX overwrites the Soggfy installation.

All possible SpotX parameters are listed here: https://github.com/SpotX-Official/SpotX/discussions/60

**Comment by Rafiuth** [comment]
Thank you both for this detailed report. I've updated the latest release to automatically set the streaming quality to the highest available at startup so this should no longer be an issue.

**Comment by HanaMcHanaface** [comment]
Awesome!! 😊
